services:
  postgresql:
    image: postgres:16.4
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/local/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
